[package]
name = "SwiftyRipgrep"
version = "0.1.0"
edition = "2021"

[lib]
name = "SwiftyRipgrep"
crate-type = [ "staticlib" ]

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
grep = "0.2"
swift-bridge = "0.1.55"
ripgrep = "13.0.0"
