[toolchain]
channel = "stable"
targets = [
    "aarch64-apple-ios",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
     "aarch64-apple-ios-sim",
     "x86_64-apple-ios-macabi",
     "aarch64-apple-ios-macabi",
     "x86_64-apple-watchos-sim",
     "aarch64-apple-watchos-sim",
     "arm64_32-apple-watchos"
]
